"""updating backref

Revision ID: 04a9f56ec62e
Revises: 1fd98133fa52
Create Date: 2023-08-19 15:30:21.649220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a9f56ec62e'
down_revision = '1fd98133fa52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
