"""updating backref

Revision ID: 1fd98133fa52
Revises: ad5d27f56399
Create Date: 2023-08-19 15:28:17.845390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd98133fa52'
down_revision = 'ad5d27f56399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
