"""updating backref

Revision ID: 2cc98af71ec1
Revises: 4ec790c29763
Create Date: 2023-08-19 14:52:05.029796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc98af71ec1'
down_revision = '4ec790c29763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
