"""updating backref

Revision ID: ad5d27f56399
Revises: ae79b7345e83
Create Date: 2023-08-19 15:26:03.268430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5d27f56399'
down_revision = 'ae79b7345e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
