"""updating backref

Revision ID: ae79b7345e83
Revises: f5b4247cf6eb
Create Date: 2023-08-19 15:24:56.148016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae79b7345e83'
down_revision = 'f5b4247cf6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
