"""updating backref

Revision ID: f5b4247cf6eb
Revises: 2cc98af71ec1
Create Date: 2023-08-19 15:15:22.844441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b4247cf6eb'
down_revision = '2cc98af71ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
